### ISSUE TITLE
Cannot access request body on some endpoints

### ISSUE THREAD

**Issue by ArnyminerZ** [expressjs/expressjs.com#1375]
Hi, i'm developing a REST API with express. I'm using the `body-parser` package to accept both url encoded and json bodies. It works perfectly on all endpoints except one, which throws `body` as undefined. I've printed the request on the console, and it shows there's a body:
```
  ...
    [Symbol(kUniqueHeaders)]: null
  },
  body: { nif: '**C', password: 'test' },
   _body: true,
   length: undefined,
  ...
```
My code is:
```javascript
import express from 'express';
import bodyParser from 'body-parser';

...

const app = express();

app.use(bodyParser.json({strict: false}));
app.use(bodyParser.urlencoded({extended: true}));
...
app.post('/v1/user/change_password', changePassword);
```
And on another file:
```javascript
export const changePassword = async (req, res) => {
    info('Change password request:', req);
    info(`Request body (${req._body}):`, req.body);
    const body = req.body;
    /** @type {string|null} */
    const nif = body['nif'];
    /** @type {string|null} */
    const password = body['password'];
    
    ...
};
```
On the console I receive:
```
Request body (undefined): undefined
```
And of course, a `TypeError`:
```
TypeError: Cannot read properties of undefined (reading 'nif')
```
It works perfectly on all the other endpoints, and they are exactly the same. What can be wrong? Thank you in advance.

**Edit:** I'm using `body-parser: ^1.20.1` and `express: ^4.18.2`.

**Comment by ArnyminerZ** [comment]
I've just realized by cleaning logs that the method is being called twice. I'm getting those logs:
```
Request body (true): { nif: '**C', password: 'test' }
Request body (undefined): undefined
Could not change password. Error: TypeError: Cannot read properties of undefined (reading 'nif')
   at changePassword (file:///usr/src/app/src/endpoints/user.js:90:21)
   at changePassword (file:///usr/src/app/src/endpoints/user.js:99:15)
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
   at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)
   at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:114:3)
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
   at /usr/src/app/node_modules/express/lib/router/index.js:284:15
   at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
   at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
   at file:///usr/src/app/node_modules/express-rate-limit/dist/index.mjs:194:5
```
By the way, I'm using curl to make the requests:
```shell
curl -X POST -H "Content-Type: application/json" -d '{"nif":"**C","password":"test"}' http://localhost:3000/v1/user/change_password
```

**Comment by ArnyminerZ** [comment]
My bad, I was importing a function with the same name, and it was not calling the correct one.
