### ISSUE TITLE
Installing as described in the guide fails. 

### ISSUE THREAD

**Issue by geon** [expressjs/expressjs.com#18]
In the guide: http://expressjs.com/guide.html

The package.json contains

```
{
  "name": "hello-world",
  "description": "hello world test app",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "express": "3.0.0"
  }
}
```

but the command

```
$ npm install
```

fails on a fresh node installation. (iMac, OS X 10.7.4)

Changing the package.json to

```
{
  "name": "hello-world",
  "description": "hello world test app",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "express": "3.0"
  }
}
```

works.

Console:

```
iMac:hello-world geon$ npm install
npm WARN package.json hello-world@0.0.1 No README.md file found!
npm http GET https://registry.npmjs.org/express/3.0.0
npm http 404 https://registry.npmjs.org/express/3.0.0
npm ERR! Error: version not found: 3.0.0 : express/3.0.0
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:14)
npm ERR!     at Request.init.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/main.js:120:22)
npm ERR!     at Request.EventEmitter.emit (events.js:91:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:555:16)
npm ERR!     at Request.EventEmitter.emit (events.js:88:17)
npm ERR!     at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (/usr/local/lib/node_modules/npm/node_modules/request/main.js:517:14)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:115:20)
npm ERR!     at IncomingMessage._emitEnd (http.js:366:10)
npm ERR!     at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
npm ERR!     at CleartextStream.socketOnData (http.js:1356:20)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 11.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/geon/Eget/node/hello-world
npm ERR! node -v v0.8.4
npm ERR! npm -v 1.1.45
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/geon/Eget/node/hello-world/npm-debug.log
npm ERR! not ok code 0
```

**Comment by tj** [comment]
fixed
