### ISSUE TITLE
Case sensitivity in documentation files

### ISSUE THREAD

**Issue by joepie91** [expressjs/expressjs.com#297]
While setting up the repository locally in order to contribute a fix, I ran across the following issue:

```
sven@linux-etoq:~/projects/expressjs.com> make
./node_modules/.bin/jade --path 3x/api.jade < 3x/api.jade > 3x/api.html
./node_modules/.bin/jade --path 4x/api.jade < 4x/api.jade > 4x/api.html

/home/sven/projects/expressjs.com/node_modules/jade/lib/runtime.js:202
  throw err;
        ^
Error: 4x/en/api/app.jade:43
    41| section
    42|   h3(id='app.METHOD') app.METHOD(path, [callback...], callback)
  > 43|   include:md ./app-method.md
    44| 
    45| section
    46|   h3(id='app.all') app.all(path, [callback...], callback)

ENOENT, no such file or directory '4x/en/api/app-method.md'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Parser.parseInclude (/home/sven/projects/expressjs.com/node_modules/jade/lib/parser.js:567:20)
    at Parser.parseExpr (/home/sven/projects/expressjs.com/node_modules/jade/lib/parser.js:223:21)
    at Parser.block (/home/sven/projects/expressjs.com/node_modules/jade/lib/parser.js:707:25)
    at Parser.tag (/home/sven/projects/expressjs.com/node_modules/jade/lib/parser.js:816:24)
    at Parser.parseTag (/home/sven/projects/expressjs.com/node_modules/jade/lib/parser.js:737:17)
    at Parser.parseExpr (/home/sven/projects/expressjs.com/node_modules/jade/lib/parser.js:211:21)
    at Parser.parse (/home/sven/projects/expressjs.com/node_modules/jade/lib/parser.js:122:25)
    at Parser.parseInclude (/home/sven/projects/expressjs.com/node_modules/jade/lib/parser.js:594:22)
make: *** [4x/api.html] Error 8
```

While `4x/en/api/app-method.md` does not exist, `4x/en/api/app-METHOD.md` does. It would seem that case sensitivity is not taken into account by the maintainer of the website - using a Windows system, perhaps?

To make the build system function correctly on all systems, either case sensitivity should be taken into account throughout the build files, or all filenames should be left as lowercase.

**Comment by dougwilson** [comment]
> It would seem that case sensitivity is not taken into account by the maintainer of the website - using a Windows system, perhaps?

The builder uses Mac OS X, which comes configured with a case-insensitive file system just like Windows these days. This should be fixed, so the file names match what is checked in, yes.

**Comment by joepie91** [comment]
Ah, right, I wasn't sure whether OS X had case sensitivity or not. That would explain it.

**Comment by hacksparrow** [comment]
Thanks for reporting, fixing it.

**Comment by joepie91** [comment]
Hmm, I was just looking at 2804f0b859c6aa1c0e4ab2ab2fab9e258688cb33 - is this the only commit dealing with this issue, or am I missing something? If I recall correctly, the were a few other potential case-sensitivity issues through the documentation files as well.
