### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by macOneOone** [expressjs/expressjs.com#761]
Hey frineds, I'v havings this error while i'm trying to run the express with node or forever js... i don't get y it's happing... can you give me an Help Please... i'v one app in prodution... 
```
TypeError: Cannot read property 'length' of undefined
    at pathtoRegexp (c:\api\v1\node_modules\path-to-regexp\index.js:63:48)
    at new Layer (c:\api\v1\node_modules\express\lib\router\layer.js:45:17)
    at Function.route (c:\api\v1\node_modules\express\lib\router\index.js:494:15)
    at EventEmitter.app.(anonymous function) [as get] (c:\api\v1\node_modules\express\lib\application.js:480:30)
    at Object.<anonymous> (c:\api\v1\server.js:33:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
error: Forever detected script exited with code: 1
error: Script restart attempt #174
```

**Comment by dougwilson** [comment]
Hi @macOneOone please stop by our support channel for assistance: https://gitter.im/expressjs/express

**Comment by macOneOone** [comment]
Yeah i will

**Comment by Harshit369** [comment]
Hi! sorry to poke you, but any solution for this?

Thanks.

**Comment by stroupjason** [comment]
Please share fix, thank you.

**Comment by Harshit369** [comment]
@stroupjason what I found was,  I was passing **undefined** path string to one of the routes.

**Comment by distupid** [comment]
in my case check .routes()   and  .route()
