### ISSUE TITLE
Promise created in handler but not returned from it 

### ISSUE THREAD

**Issue by nstuyvesant** [expressjs/expressjs.com#767]
Been getting warnings about promises in handlers within expressjs but not returned from them. Would it make sense to ensure that they return the promise as a best practice (even though Express appears to be working as expected)?

Here's a trace...
```
(node:32067) Warning: a promise was created in a handler at /Users/nates/Documents/Development/shy/node_modules/express/lib/router/layer.js:95:5 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.bind (/Users/nates/Documents/Development/shy/node_modules/bluebird/js/release/bind.js:65:20)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Model.findAll (/Users/nates/Documents/Development/shy/node_modules/sequelize/lib/model.js:1355:18)
    at Model.findOne (/Users/nates/Documents/Development/shy/node_modules/sequelize/lib/model.js:1527:34)
    at localAuthenticate (/Users/nates/Documents/Development/shy/server/auth/local/passport.js:17:15)
    at Strategy._verify (/Users/nates/Documents/Development/shy/server/auth/local/passport.js:47:12)
    at Strategy.authenticate (/Users/nates/Documents/Development/shy/node_modules/passport-local/lib/strategy.js:90:12)
    at attempt (/Users/nates/Documents/Development/shy/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (/Users/nates/Documents/Development/shy/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at /Users/nates/Documents/Development/shy/server/auth/local/index.js:33:5
    at Layer.handle [as handle_request] (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/layer.js:95:5)
    at /Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:312:13)
    at /Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:46:12)
From previous event:
    at Promise.then (/Users/nates/Documents/Development/shy/node_modules/sequelize/lib/promise.js:21:17)
    at E4Store.get (/Users/nates/Documents/Development/shy/node_modules/express-sequelize-session/lib/e4store.js:56:12)
    at session (/Users/nates/Documents/Development/shy/node_modules/express-session/index.js:444:11)
    at Layer.handle [as handle_request] (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:312:13)
    at /Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:271:10)
    at initialize (/Users/nates/Documents/Development/shy/node_modules/passport/lib/middleware/initialize.js:53:5)
    at Layer.handle [as handle_request] (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:312:13)
    at /Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:271:10)
    at cookieParser (/Users/nates/Documents/Development/shy/node_modules/cookie-parser/index.js:70:5)
    at Layer.handle [as handle_request] (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:312:13)
    at /Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:271:10)
    at methodOverride (/Users/nates/Documents/Development/shy/node_modules/method-override/index.js:79:5)
    at Layer.handle [as handle_request] (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:312:13)
    at /Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/nates/Documents/Development/shy/node_modules/express/lib/router/index.js:330:12)
```

**Comment by hacksparrow** [comment]
That's the responsibility of the handler to resolve or reject the promise.

For general queries and discussions about Express and webdev join us at our [official Gitter channel](https://gitter.im/expressjs/express).
